import React from 'react'
import type { NextPage } from "next";
import ItemList from "../components/itemsList";
import Layout from "../components/layout";
import Head from "next/head";
import { url, item } from "../app/types_constant";
import { Box, Spinner } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import InfiniteScroll from "react-infinite-scroll-component";

const Home: NextPage = () => {
  const fetcher = (url: string) => fetch(url).then((res) => res.json());
  const [items, setItems] = useState<item[]>([]);
  const [offset, setOffset] = useState<number>(0)
  const fetchItems = () => {
    fetcher(`${url}offset=${offset}&limit=6`).then((data) => {
      console.log(data);
      if (items !== undefined) setItems([...items, ...data]);
      else setItems(data);

      setOffset(offset + 6)
    });
  };

  useEffect(fetchItems, []);
  return (
    <>
      <Head>
        <title>Fake Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/325/department-store_1f3ec.png"
        />
      </Head>
      <Layout />

      <Box>
        <InfiniteScroll
          style={{ overflow: "hidden" }}
          dataLength={items.length} //This is important field to render the next data
          next={fetchItems}
          hasMore={true}
          loader={
            <Spinner
              thickness="4px"
              speed="0.65s"
              emptyColor="gray.200"
              color="blue.500"
              size="xl"
              mx="auto"
              display="grid"
              justifyContent="center"
            />
          }
        >
          <ItemList items={items} />
        </InfiniteScroll>
      </Box>
    </>
  );
};

export default Home;
