import type { NextPage } from "next";
import ItemList from "../components/itemsList";
import Layout from '../components/layout'
import Head from "next/head";
import useSWR from "swr";
import { url, item } from '../app/types_constant'
import { Box } from "@chakra-ui/react";

const Home: NextPage = () => {
  const fetcher = (url: string) => fetch(url).then((res) => res.json());
  const { data } = useSWR<item[] | undefined>(
    url,
    fetcher
  );
  return (
    <Box>
      <Head>
        <title>Fake Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/325/department-store_1f3ec.png" />
      </Head>
      <Layout />

      <main>{!data ? "nooo" : <ItemList items={data} />}</main>
    </Box>
  );
};

export default Home;
